name: BDD

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  bdd:
    runs-on: ubuntu-latest
    env:
      A11Y_SKIP_DOMAINS: 'opensource-demo.orangehrmlive.com'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build TypeScript
        run: npm run bdd:build

      - name: Run BDD
        run: npm run bdd:run

      - name: Upload Cucumber report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: reports/cucumber-report.html

      - name: Upload a11y results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: a11y-reports
          path: reports/a11y/
